insert into author values (1, "Alberto Raposo", null);
insert into author values (2, "Alcantara Rodrigues", null);
insert into author values (3, "Alejandro Zunino", null);
insert into author values (4, "Alexander Hubmann-Haidvogel", null);
insert into author values (5, "Alexandre Araújo", null);
insert into author values (6, "Alexandre Cardoso", null);
insert into author values (7, "Alexandre Martins Ferreira de Sousa", null);
insert into author values (8, "Alfredo Gomes De Araujo Neto", null);
insert into author values (9, "Alfredo Teyseyre", null);
insert into author values (10, "Aline Alves Silva", null);
insert into author values (11, "Aline Silveira", null);
insert into author values (12, "Ana Carolina Bertoletti De Marchi", null);
insert into author values (13, "Ana Maria Pereira Cardoso", null);
insert into author values (14, "Ana Oliveira", null);
insert into author values (15, "Ana Waki", null);
insert into author values (16, "Anders Hedman", null);
insert into author values (17, "Anna De Liddo", null);
insert into author values (18, "Antonio Augusto Prates", null);
insert into author values (19, "Antonio Diaz Tula", null);
insert into author values (20, "Antonio Loureiro", null);
insert into author values (21, "Ariel Soares Teles", null);
insert into author values (22, "Arikleyton De Oliveira Ferreira", null);
insert into author values (23, "Arno Scharl", null);
insert into author values (24, "Aron D. Lopes", null);
insert into author values (25, "Aron Lopes", null);
insert into author values (26, "Artur Kronbauer", null);
insert into author values (27, "Bernardo Reis", null);
insert into author values (28, "Betty Chavez Boza", null);
insert into author values (29, "Camila Maia", null);
insert into author values (30, "Carlos H. Morimoto", null);
insert into author values (31, "Carlos Hitoshi Morimoto", null);
insert into author values (32, "Carlos Rios", null);
insert into author values (33, "Carlos Ynoguti", null);
insert into author values (34, "Carmina Reyes", null);
insert into author values (35, "Catia Ferreira", null);
insert into author values (36, "Cecilia Baranauskas", null);
insert into author values (37, "Celso Santos", null);
insert into author values (38, "Clarisse De Souza", null);
insert into author values (39, "Claudia Berti", null);
insert into author values (40, "Claudio Santos Pinhanez", null);
insert into author values (41, "Cristiane Ellwanger", null);
insert into author values (42, "Cristiane Neri Nobre", null);
insert into author values (43, "Cristiano Maciel", null);
insert into author values (44, "Cristina Paludo Santos", null);
insert into author values (45, "Daiana Biduski", null);
insert into author values (46, "Daniela Falcone", null);
insert into author values (47, "Daniela Godoy", null);
insert into author values (48, "Diego Augusto de Faria Barros", null);
insert into author values (49, "Diego Bevilaqua", null);
insert into author values (50, "Diferson Machado", null);
insert into author values (51, "Eliane Lucia Colussi", null);
insert into author values (52, "Elizabeth Furtado", null);
insert into author values (53, "Emanuelly Barros", null);
insert into author values (54, "Eunice Nunes", null);
insert into author values (55, "Fátima Nunes", null);
insert into author values (56, "Fabricio Benevenuto", null);
insert into author values (57, "Felipe Breyer", null);
insert into author values (58, "Fernanda C. Ribeiro", null);
insert into author values (59, "Filipe M. S. De Campos", null);
insert into author values (60, "Flavio Coutinho", null);
insert into author values (61, "Francisco José Da Silva Silva", null);
insert into author values (62, "Guilherme Fujiyoshi", null);
insert into author values (63, "Guilherme Moreira", null);
insert into author values (64, "Harith Alani", null);
insert into author values (65, "Helena Tobiasson", null);
insert into author values (66, "Henrique Taunay", null);
insert into author values (67, "Horácio Pastor Soares", null);
insert into author values (68, "Horácio Soares", null);
insert into author values (69, "Isabela Gasparini", null);
insert into author values (70, "Isaque Elcio Souza", null);
insert into author values (71, "Jaime Sánchez", null);
insert into author values (72, "Jano Moreira de Souza", null);
insert into author values (73, "Jean Vanderdonckt", null);
insert into author values (74, "Jessica Colnago", null);
insert into author values (75, "José Antonio Gonçalves Motta", null);
insert into author values (76, "José Luiz Dos Anjos Rosa", null);
insert into author values (77, "Juan Manuel Rodriguez", null);
insert into author values (78, "Judith Kelner", null);
insert into author values (79, "Julian E Gutierrez Posada", null);
insert into author values (80, "Juliana Jansen Ferreira", null);
insert into author values (81, "Julio Reis", null);
insert into author values (82, "Junia Anacleto", null);
insert into author values (83, "Jussara Almeida", null);
insert into author values (84, "Kamila Rodrigues", null);
insert into author values (85, "Lara Piccolo", null);
insert into author values (86, "Leonardo Botega", null);
insert into author values (87, "Leonardo Nascimento", null);
insert into author values (88, "Leonelo Almeida", null);
insert into author values (89, "Letícia Régis Di Maio", null);
insert into author values (90, "Licínio Roque", null);
insert into author values (91, "Luan Jr. Costa", null);
insert into author values (92, "Lucas Bastos", null);
insert into author values (93, "Lucas Bocanegra", null);
insert into author values (94, "Lucas Felipe Da Cunha", null);
insert into author values (95, "Luciana Espindola", null);
insert into author values (96, "Luciana Salgado", null);
insert into author values (97, "Luis A Vasconcelos", null);
insert into author values (98, "M Cecília C Baranauskas", null);
insert into author values (99, "Marcelle Silva", null);
insert into author values (100, "Marcelo Pimenta", null);
insert into author values (101, "Marcia De Borba Campos", null);
insert into author values (102, "Marcos Alves Dos Santos", null);
insert into author values (103, "Marcos Hideshi Kimura", null);
insert into author values (104, "Marcos Prates", null);
insert into author values (105, "Maria Villela", null);
insert into author values (106, "Matías Espinoza", null);
insert into author values (107, "Mateus Trombetta", null);
insert into author values (108, "Melise M. V. de Paula", null);
insert into author values (109, "Milene Silveira", null);
insert into author values (110, "Miriam Fernandez", null);
insert into author values (111, "Muriane Zimmer", null);
insert into author values (112, "Natália Oliveira", null);
insert into author values (113, "Natasha Valentim", null);
insert into author values (114, "Ney Wagner Freitas Cavalcante", null);
insert into author values (115, "Nirvana Antonio", null);
insert into author values (116, "Omar Guimarães Junior", null);
insert into author values (117, "Ozonias Junior", null);
insert into author values (118, "Pamela Levy", null);
insert into author values (119, "Paulo Afonso Parreira Junior", null);
insert into author values (120, "Pedro Henrique Batista Ruas Da Silveira", null);
insert into author values (121, "Pedro Olmo Vaz de Melo", null);
insert into author values (122, "Pedro Silva", null);
insert into author values (123, "Phillipe Marcell", null);
insert into author values (124, "Pollyanna Goncalves", null);
insert into author values (125, "Priscila Souza", null);
insert into author values (126, "Priscilla Braz", null);
insert into author values (127, "Rafael Almeida", null);
insert into author values (128, "Rafael Brandão", null);
insert into author values (129, "Rafael Santos", null);
insert into author values (130, "Rafael Testa", null);
insert into author values (131, "Ramon Mayor Martins", null);
insert into author values (132, "Raquel Cardoso de Melo Minardi", null);
insert into author values (133, "Raquel Oliveira Prates", null);
insert into author values (134, "Raquel Prates", null);
insert into author values (135, "Regina Araújo", null);
insert into author values (136, "Renato Cerqueira", null);
insert into author values (137, "Rener Silva", null);
insert into author values (138, "Rogério Abreu de Paula", null);
insert into author values (139, "Rogério Caetano", null);
insert into author values (140, "Rogério Xavier", null);
insert into author values (141, "Silvia Schiaffino", null);
insert into author values (142, "Simone Bacellar Leal Ferreira", null);
insert into author values (143, "Simone Diniz Junqueira Barbosa", null);
insert into author values (144, "Simone Xavier", null);
insert into author values (145, "Suzanne Kieffer", null);
insert into author values (146, "Taciana Pontual Falcão", null);
insert into author values (147, "Tatiana Alencar", null);
insert into author values (148, "Tayana Conte", null);
insert into author values (149, "Thiago Silva", null);
insert into author values (150, "Ugo Sangiorgi", null);
insert into author values (151, "Vagner Figueredo De Santana", null);
insert into author values (152, "Vanessa R M. L. Maike", null);
insert into author values (153, "Vania Neris", null);
insert into author values (154, "Vicente Neto", null);
insert into author values (155, "Vinícius Carvalho", null);
insert into author values (156, "Vinícius Gonçalves", null);
insert into author values (157, "Vinicius C", null);
insert into author values (158, "Vinicius C. Pereira", null);
insert into author values (159, "Williamson Silva", null);
insert into author values (160, "Yngve Sundblad", null);
insert into author values (161, "Yuska Paola", null);
insert into author values (162, "Marcos Martins", "UERJ");
insert into author values (163, "Amanda Meincke Melo", "UNIPAMPA");
insert into author values (164, "Paulo Urbano", "CESAR");
insert into author values (165, "Rodrigo Cruz", "CESAR");
insert into author values (166, "Tamara Duarte", "CESAR");
insert into author values (167, "Celmar Guimarães Da Silva", "UNICAMP");
insert into author values (168, "Bruno Santana Da Silva", "UFRN");